format = """$hostname$time $directory $cmd_duration $memory_usage
$git_branch$character"""

[directory]
truncation_length = 0
truncate_to_repo = false
format = "[<](dimmed cyan)[$path](blue)[>](dimmed cyan)"

[cmd_duration]
format = "[$duration](dimmed cyan)"
min_time = 5
show_milliseconds = true

[character]
success_symbol = "[»](dimmed green)[»](green)[»](fg:226)" # brights break
error_symbol = "[»](dimmed red)[»](red)[»](fg:196)"
vicmd_symbol = "[v](fg:11)"

[memory_usage]
threshold = 1
format = "[$ram_pct](dimmed cyan)"
disabled = false

[time]
format = "[$time](fg:112)"
disabled = false

[hostname]
format = "[ssh]($style)[->](bold dimmed green)[$hostname]($style) "
style = "underline red"
ssh_only = true

[git_branch]
format = "<[$branch]($style)> "
style = "purple"

[git_commit]
disabled = true
[git_state]
disabled = true
[git_status]
disabled = true

[nodejs]
disabled = true
[python]
disabled = true
[rust]
disabled = true